# Generated by Django 3.2.5 on 2021-08-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0002_auto_20210809_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproxysalmacenados',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mproxysdisponibles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
