# Generated by Django 3.2.5 on 2021-08-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0003_auto_20210814_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRegistros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=120)),
                ('puerto', models.CharField(max_length=120)),
                ('protocolo', models.CharField(max_length=120)),
                ('fecha', models.CharField(max_length=120)),
                ('almacenado', models.BooleanField()),
                ('estado_respuesta', models.BooleanField()),
                ('tiempo_respuesta', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
