# Generated by Django 3.2.5 on 2021-08-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0004_mregistros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mregistros',
            name='tiempo_respuesta',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
    ]
